/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-background": "#131b2e",
        "on-error": "#ffffff",
        "secondary-container": "#e0f2fe",
        "on-secondary-container": "#00476e",
        "secondary": "#0284c7",
        "on-tertiary-fixed": "#0f0069",
        "on-surface-variant": "#475569",
        "on-secondary-fixed-variant": "#004b73",
        "background": "#f8fafc",
        "surface-container-highest": "#e2e8f0",
        "error-container": "#fee2e2",
        "on-tertiary-container": "#fffaff",
        "surface": "#ffffff",
        "primary-container": "#e11d48",
        "surface-container-low": "#f8fafc",
        "on-secondary-fixed": "#001d31",
        "inverse-surface": "#1e293b",
        "tertiary": "#4f46e5",
        "primary": "#e11d48",
        "tertiary-fixed": "#e0e7ff",
        "on-tertiary": "#ffffff",
        "on-surface": "#0f172a",
        "secondary-fixed-dim": "#bae6fd",
        "surface-bright": "#ffffff",
        "on-error-container": "#991b1b",
        "surface-container-high": "#edf2f7",
        "tertiary-fixed-dim": "#c7d2fe",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#e0f2fe",
        "surface-variant": "#f1f5f9",
        "on-primary-fixed": "#40000c",
        "primary-fixed": "#ffe4e6",
        "error": "#dc2626",
        "inverse-on-surface": "#f8fafc",
        "on-primary-container": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#f1f5f9",
        "inverse-primary": "#fda4af",
        "surface-container": "#ffffff",
        "on-tertiary-fixed-variant": "#3730a3",
        "primary-fixed-dim": "#fecdd3",
        "on-primary-fixed-variant": "#9f1239",
        "outline-variant": "#e2e8f0",
        "on-primary": "#ffffff",
        "surface-tint": "#e11d48",
        "tertiary-container": "#6366f1",
        "outline": "#cbd5e1"
      },
      borderRadius: {
        DEFAULT: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        gutter: "1.5rem",
        "margin-mobile": "1rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "1rem",
        "space-md": "1rem",
        margin: "2rem",
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "gutter-desktop": "2rem",
        "margin-desktop": "3rem"
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "Inter", "system-ui", "sans-serif"],
        mono: ["'JetBrains Mono'", "ui-monospace", "monospace"],
        "label-sm": ["'Plus Jakarta Sans'"],
        "headline-lg": ["'Plus Jakarta Sans'"],
        "headline-sm": ["'Plus Jakarta Sans'"],
        "display-hero-mobile": ["'Plus Jakarta Sans'"],
        "headline-md": ["'Plus Jakarta Sans'"],
        "ipa-body": ["'JetBrains Mono'"],
        "body-sm": ["'Plus Jakarta Sans'"],
        "headline-lg-mobile": ["'Plus Jakarta Sans'"],
        "body-lg": ["'Plus Jakarta Sans'"],
        "label-md": ["'Plus Jakarta Sans'"],
        "body-md": ["'Plus Jakarta Sans'"],
        "display-hero": ["'Plus Jakarta Sans'"],
        "telemetry-data": ["'JetBrains Mono'"],
        "ipa-display": ["'JetBrains Mono'"],
        "ipa-inline": ["'JetBrains Mono'"],
        "label-mono": ["'JetBrains Mono'"]
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-hero-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "ipa-body": ["16px", { lineHeight: "24px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "display-hero": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "telemetry-data": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "ipa-display": ["24px", { lineHeight: "32px", letterSpacing: "0.04em", fontWeight: "600" }],
        "ipa-inline": ["15px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-mono": ["11px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" }]
      }
    }
  },
  plugins: []
};
