// Utilities for exporting backlog to Jira/GitHub CSV, Markdown/Notion, and Raw JSON

/**
 * Escapes a cell value for CSV format according to RFC 4180
 */
function escapeCsvCell(val) {
  if (val === null || val === undefined) return '""';
  const str = String(val);
  // If contains commas, quotes, or newlines, wrap in quotes and escape internal quotes
  if (str.includes(',') || str.includes('"') || str.includes('\n') || str.includes('\r')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return `"${str}"`;
}

/**
 * Generates Jira / GitHub compatible CSV
 */
export function generateJiraCsv(project) {
  const headers = [
    'Issue Type',
    'Issue key',
    'Summary',
    'Description',
    'Epic Name',
    'Priority',
    'Status',
    'Story Points',
    'Persona',
    'Acceptance Criteria',
    'Technical Tasks'
  ];

  const rows = [];

  // Map epics first
  project.epics.forEach(epic => {
    rows.push([
      'Epic',
      epic.id,
      epic.title,
      epic.description || '',
      epic.title,
      'Medium',
      'To Do',
      '',
      '',
      '',
      ''
    ]);
  });

  // Map stories
  project.stories.forEach(story => {
    const parentEpic = project.epics.find(e => e.id === story.epicId);
    const epicTitle = parentEpic ? parentEpic.title : 'General';

    const narrative = `As a ${story.persona || 'user'}, I want to ${story.action || ''}, so that ${story.value || ''}.`;
    
    const acText = (story.acceptanceCriteria || [])
      .map(ac => `[${ac.completed ? 'x' : ' '}] Given ${ac.given || ''} When ${ac.when || ''} Then ${ac.then || ''}`)
      .join('\n');

    const tasksText = (story.technicalTasks || [])
      .map(t => `[${t.completed ? 'x' : ' '}] [${t.category}] ${t.title}`)
      .join('\n');

    const fullDescription = `${narrative}\n\n${story.notes ? `Notes:\n${story.notes}\n\n` : ''}Acceptance Criteria:\n${acText}\n\nTechnical Tasks:\n${tasksText}`;

    // Map priority to standard Jira levels
    const priorityMap = {
      must: 'Highest',
      should: 'High',
      could: 'Medium',
      wont: 'Low'
    };

    const statusMap = {
      backlog: 'Backlog',
      todo: 'To Do',
      'in-progress': 'In Progress',
      done: 'Done'
    };

    rows.push([
      'Story',
      story.id,
      story.title,
      fullDescription,
      epicTitle,
      priorityMap[story.priority] || 'Medium',
      statusMap[story.status] || 'To Do',
      story.points || '',
      story.persona || '',
      acText,
      tasksText
    ]);
  });

  const csvContent = [
    headers.map(escapeCsvCell).join(','),
    ...rows.map(row => row.map(escapeCsvCell).join(','))
  ].join('\r\n');

  return csvContent;
}

/**
 * Generates beautifully formatted Markdown for Notion or GitHub Wiki
 */
export function generateMarkdown(project) {
  let md = `# ${project.name || 'StoryMapper Backlog'}\n\n`;
  if (project.description) {
    md += `> ${project.description}\n\n`;
  }

  // Quick stats summary
  const totalEpics = project.epics.length;
  const totalStories = project.stories.length;
  const totalPoints = project.stories.reduce((acc, s) => acc + (Number(s.points) || 0), 0);
  const doneStories = project.stories.filter(s => s.status === 'done').length;

  md += `## 📊 Project Overview\n\n`;
  md += `- **Epics:** ${totalEpics}\n`;
  md += `- **Total Stories:** ${totalStories} (${doneStories} completed, ${Math.round((doneStories / (totalStories || 1)) * 100)}% progress)\n`;
  md += `- **Total Story Points:** ${totalPoints} pts\n`;
  md += `- **Generated by:** StoryMapper Agile Studio\n\n`;

  md += `## 🗺️ Epics & User Stories\n\n`;

  project.epics.forEach((epic, idx) => {
    md += `### Epic ${idx + 1}: ${epic.title}\n`;
    if (epic.description) {
      md += `*${epic.description}*\n\n`;
    }

    const epicStories = project.stories.filter(s => s.epicId === epic.id);

    if (epicStories.length === 0) {
      md += `*No user stories currently defined for this epic.*\n\n`;
      return;
    }

    epicStories.forEach(story => {
      const priorityLabel = story.priority ? story.priority.toUpperCase() : 'SHOULD';
      const statusLabel = (story.status || 'todo').toUpperCase();
      const pointsLabel = story.points ? `${story.points} pts (${story.size || 'M'})` : 'Unestimated';

      md += `#### [${story.id}] ${story.title}\n\n`;
      md += `| Priority | Status | Estimate | Persona |\n`;
      md += `| :--- | :--- | :--- | :--- |\n`;
      md += `| \`${priorityLabel}\` | **${statusLabel}** | ${pointsLabel} | ${story.persona || 'User'} |\n\n`;

      md += `**User Story Formulation:**\n`;
      md += `> **As a** ${story.persona || 'user'},\n`;
      md += `> **I want to** ${story.action || story.title},\n`;
      md += `> **So that** ${story.value || 'I achieve my goal'}.\n\n`;

      if (story.acceptanceCriteria && story.acceptanceCriteria.length > 0) {
        md += `**Acceptance Criteria (Gherkin):**\n`;
        story.acceptanceCriteria.forEach(ac => {
          const checked = ac.completed ? '[x]' : '[ ]';
          md += `- ${checked} **Given** ${ac.given}, **When** ${ac.when}, **Then** ${ac.then}\n`;
        });
        md += `\n`;
      }

      if (story.technicalTasks && story.technicalTasks.length > 0) {
        md += `**Technical Tasks:**\n`;
        story.technicalTasks.forEach(t => {
          const checked = t.completed ? '[x]' : '[ ]';
          md += `- ${checked} \`[${t.category || 'General'}]\` ${t.title}\n`;
        });
        md += `\n`;
      }

      if (story.notes) {
        md += `*Implementation Notes:* ${story.notes}\n\n`;
      }

      md += `---\n\n`;
    });
  });

  return md;
}

/**
 * Generates sanitized raw JSON
 */
export function generateRawJson(project) {
  const exportPayload = {
    schemaVersion: '1.0.0',
    exportedAt: new Date().toISOString(),
    project: {
      id: project.id,
      name: project.name,
      description: project.description,
      epics: project.epics,
      stories: project.stories
    }
  };
  return JSON.stringify(exportPayload, null, 2);
}

/**
 * Triggers a file download in the browser
 */
export function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Safe clipboard copy with fallback
 */
export async function copyToClipboard(text) {
  if (navigator.clipboard && navigator.clipboard.writeText) {
    await navigator.clipboard.writeText(text);
    return true;
  }
  // Fallback for older browsers
  const textArea = document.createElement('textarea');
  textArea.value = text;
  textArea.style.position = 'fixed';
  textArea.style.left = '-9999px';
  document.body.appendChild(textArea);
  textArea.focus();
  textArea.select();
  const successful = document.execCommand('copy');
  document.body.removeChild(textArea);
  return successful;
}
